### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by murmub23** [gerisonsabino/bing_autosearch#1]
I tried opening the site, but it throwed an 404 error.
It's opening on my old laptop and phone, but on a newer phone and PC, it doesn't open.

It stopped working after the index.html file was updated 2 days ago.
![IMG_20230704_085451_503](https://github.com/gerisonsabino/bing_autosearch/assets/35886489/eb672e64-07b6-4876-95a8-bf81dbd65966)

**Comment by gerisonsabino** [comment]
Hey, @BlumeJP5!
Check the typed/open URL, after the ".../bing_autosearch/" there are other digits. Just remove them and then it will open.

![image](https://github.com/gerisonsabino/bing_autosearch/assets/20420661/75e29885-932c-4b0e-ac67-919b9bfa8869)

Anyway, below is the link in the correct format so you can try again.

https://gerisonsabino.com/bing_autosearch/

**Comment by gerisonsabino** [comment]
In fact, I think I managed to identify your problem, it's about opening via external links, such as a Google search for example. I will bring a fix! Many thanks!

**Comment by murmub23** [comment]
> In fact, I think I managed to identify your problem, it's about opening via external links, such as a Google search for example. I will bring a fix! Many thanks!

Yea, I tried to open through your link, but it didn't work. It randomly adds those characters to the address and even removing them gives me a 404 error.
Anyways, it very nice of you to take attention on that. Thank You. 👍

**Comment by gerisonsabino** [comment]
I just committed a hotfix to solve. Thanks again for reporting the issue!

**Comment by murmub23** [comment]
> I just committed a hotfix to solve. Thanks again for reporting the issue!

Thanks Man! 
Really appreciate it.
