### ISSUE TITLE
enhancement: auto mobile search 

### ISSUE THREAD

**Issue by Bakuteria-Ocha** [gerisonsabino/bing_autosearch#2]
Hi I'm wondering if it possible to add a function of simulate mobile search by use a mobile browser user-agent?

And thank u for your program. Its really easy to use.

**Comment by gerisonsabino** [comment]
Hi, @Bakuteria-Ocha. Thanks!

Unfortunately I don't think so, the Bing page takes other factors besides the user-agent to present the mobile version and there is also no control to change it directly in the loaded Bing structure (via iframe/JS).

The only functional way to do this would be to emulate a mobile browser through the developer tools (F12) on the PC or use your smartphone to run it, this way, the loaded structure will be the mobile one and it works perfectly.
